// Code generated by microctl. If you need edit, delete this line

package mobile_fishing

var StatusCodeMsgMap = map[StatusCode]string{
	StatusCode_status_success:                "请求成功",
	StatusCode_status_internal_error:         "内部错误",
	StatusCode_status_param_error:            "参数错误",
	StatusCode_status_user_like_error:        "请勿重复点赞",
	StatusCode_status_user_collection_error:  "请勿重复收藏",
	StatusCode_status_repeat_follow_error:    "请勿重复关注",
	StatusCode_status_infomation_saldo_error: "余额不足",
	StatusCode_status_infomation_pay_error:   "支付异常",
}

func (x StatusCode) ErrMsg() string {
	msg, ok := StatusCodeMsgMap[x]
	if ok {
		return msg
	}
	return ""
}

func ServiceStatus(status *Status, statusCode StatusCode) {
	status.Code = statusCode
	status.Msg = statusCode.ErrMsg()
}
func Msg(v interface{}) string {
	switch v.(type) {
	}
	return ""
}
